site_dir: docs
docs_dir: docsrc
site_name: Host Link Communication Python API
site_url: https://fa-yoshinobu.github.io/plc-comm-hostlink-python/
theme:
  name: material
  palette:
    scheme: slate
    primary: red
plugins:
  - search
  - mkdocstrings:
      default_handler: python
exclude_docs: |
  internal_docs/**
  api/**
  maintainer/**
  validation/**

nav:
  - Overview: index.md
  - Getting Started: user/GETTING_STARTED.md
  - Supported PLC Registers: user/SUPPORTED_REGISTERS.md
  - Latest Communication Verification: user/LATEST_COMMUNICATION_VERIFICATION.md
  - User Guide: user/USER_GUIDE.md
  - API Reference: user/API_REFERENCE.md
  - Troubleshooting: user/TROUBLESHOOTING.md
  - Performance Guide: user/PERFORMANCE_GUIDE.md
  - Change Log: CHANGELOG.md
